/** Small WebP thumbnails generated by scripts/make-thumbs.mjs from public/source/{desktop,mobile}. */
export type ThumbSize = '480' | '640' | '1000' | 'm200' | 'm400' | 'm800';

/** srcset of a desktop screenshot: phones take the 640 px file, wider screens the 1000 px one. */
export const shotSrcset = (image: string | undefined) => (image ? `${thumb(image, '640')} 640w, ${thumb(image, '1000')} 1000w` : undefined);

export function thumb(image: string | undefined, size: ThumbSize): string | undefined {
  if (!image) return undefined;
  const name = image.split('/').pop()!.replace(/\.[^.]+$/, '').replace(/-(desktop|mobile)$/, '');
  return `/source/thumbs/${name}-${size}.webp`;
}
