/** Small WebP thumbnails generated by scripts/make-thumbs.mjs from public/source/{desktop,mobile}. */
export type ThumbSize = '480' | '1000' | 'm200' | 'm400' | 'm800';

export function thumb(image: string | undefined, size: ThumbSize): string | undefined {
  if (!image) return undefined;
  const name = image.split('/').pop()!.replace(/\.[^.]+$/, '').replace(/-(desktop|mobile)$/, '');
  return `/source/thumbs/${name}-${size}.webp`;
}
